#!/usr/bin/env python3
"""
PDF AI Summarizer
Extracts text from PDF and generates AI summary using Ollama
"""

import sys
import os
import json
import subprocess
from pathlib import Path

# Import our pdf_to_text function
sys.path.insert(0, '/media/tony/Drive2/Programs/pdf_to_text')
from pdf_to_text import pdf_to_text


def summarize_with_ollama(text, model="llama3.2:latest", max_chars=8000):
    """Send text to Ollama and get summary."""
    
    # Truncate text if too long (Ollama context limits)
    if len(text) > max_chars:
        text = text[:max_chars] + "\n\n[... text truncated for summary ...]"
    
    prompt = f"""You are a helpful AI that summarizes documents. 

Please provide a comprehensive summary of the following document. Include:
- Main topics and themes
- Key concepts or ideas
- Overall purpose of the document

Document:
---
{text}
---

Summary:"""

    try:
        # Call Ollama API
        result = subprocess.run(
            ["curl", "-s", "http://localhost:11434/api/generate",
             "-d", json.dumps({
                 "model": model,
                 "prompt": prompt,
                 "stream": False,
                 "options": {"temperature": 0.3}
             })],
            capture_output=True, text=True, timeout=120
        )
        
        if result.returncode == 0:
            response = json.loads(result.stdout)
            return {
                "success": True,
                "summary": response.get("response", "").strip(),
                "model": model
            }
        else:
            return {
                "success": False,
                "error": f"Ollama error: {result.stderr}"
            }
            
    except subprocess.TimeoutExpired:
        return {"success": False, "error": "Ollama request timed out"}
    except Exception as e:
        return {"success": False, "error": str(e)}


def pdf_summarize(pdf_path, model="llama3.2", summary_type="detailed", verbose=False, save_to_brain=False):
    """Full pipeline: PDF -> text -> AI summary."""
    
    # Step 1: Extract text - use central extracted folder for write-protected dirs
    if verbose:
        print(f"📄 Extracting text from: {pdf_path}")
    
    # Check if we can write to the PDF's directory
    pdf_dir = os.path.dirname(pdf_path)
    test_file = os.path.join(pdf_dir, ".write_test")
    extracted_dir = "/media/tony/Drive2/Programs/pdf_to_text/extracted/"
    
    try:
        with open(test_file, "w") as f:
            f.write("test")
        os.remove(test_file)
        output_path = None  # Use default (same dir as PDF)
    except PermissionError:
        # Can't write to PDF dir - use central extracted folder
        filename = os.path.basename(pdf_path).replace(".pdf", ".txt")
        output_path = os.path.join(extracted_dir, filename)
    
    result = pdf_to_text(pdf_path, output_path=output_path, verbose=verbose)
    
    if not result["success"]:
        return {"success": False, "error": result["error"]}
    
    # Read the extracted text
    text_path = result["output"]
    with open(text_path, 'r', encoding='utf-8') as f:
        text = f.read()
    
    if verbose:
        print(f"📝 Extracted {len(text)} characters")
        print(f"🤖 Generating {summary_type} summary with {model}...")
    
    # Step 2: Generate summary
    summary_result = summarize_with_ollama(text, model=model)
    
    if summary_result["success"]:
        summary_text = summary_result["summary"]
        
        # Step 3: Optionally save to Brain
        brain_note_id = None
        if save_to_brain:
            pdf_name = Path(pdf_path).stem
            title = f"PDF Summary: {pdf_name}"
            tags = "pdf-summary,ai-summary"
            content = f"""# {pdf_name}

**Source:** {pdf_path}
**Pages:** {result['pages']}
**Model:** {model}
**Extracted:** {len(text)} characters

---

{summary_text}

---
*Generated by PDF AI Summarizer*"""
            
            try:
                brain_result = subprocess.run(
                    ["python3", "/media/tony/Drive2/Programs/brain/brain.py", "note",
                     "--title", title, "--tags", tags, content],
                    capture_output=True, text=True, timeout=30
                )
                if brain_result.returncode == 0:
                    # Extract note ID from output
                    for line in brain_result.stdout.split('\n'):
                        if 'Added note' in line or 'ID:' in line:
                            brain_note_id = line.strip()
                            break
                    if not brain_note_id:
                        brain_note_id = "Saved to Brain"
                if verbose:
                    print(f"🧠 Brain save: {brain_result.stdout}")
            except Exception as e:
                if verbose:
                    print(f"⚠️ Brain save error: {e}")
        
        return {
            "success": True,
            "pdf": pdf_path,
            "pages": result["pages"],
            "text_file": text_path,
            "text_length": len(text),
            "summary": summary_text,
            "model": model,
            "brain_note_id": brain_note_id
        }
    else:
        return {
            "success": False,
            "error": summary_result["error"]
        }


def main():
    import argparse
    
    parser = argparse.ArgumentParser(description="PDF AI Summarizer")
    parser.add_argument("pdf_file", help="Path to PDF file")
    parser.add_argument("model", nargs="?", default="llama3.2:latest", help="Ollama model (default: llama3.2:latest)")
    parser.add_argument("summary_type", nargs="?", default="detailed", help="Summary type (brief|detailed)")
    parser.add_argument("--save-brain", action="store_true", help="Save summary to Brain")
    
    args = parser.parse_args()
    
    result = pdf_summarize(
        args.pdf_file, 
        model=args.model, 
        summary_type=args.summary_type, 
        verbose=True,
        save_to_brain=args.save_brain
    )
    
    if result["success"]:
        print(f"\n{'='*60}")
        print("📝 SUMMARY")
        print('='*60)
        print(result["summary"])
        print('='*60)
        print(f"\n✅ Summary complete!")
        print(f"   Model: {result['model']}")
        print(f"   Pages: {result['pages']}")
        print(f"   Text length: {result['text_length']} chars")
        if result.get("brain_note_id"):
            print(f"   🧠 Brain: {result['brain_note_id']}")
    else:
        print(f"\n❌ Error: {result['error']}")
        sys.exit(1)


if __name__ == "__main__":
    main()
